/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.worldgenerationproject.GUI;

import com.mycompany.worldgenerationproject.GUI.Math.Fortune.VEdge;
import com.mycompany.worldgenerationproject.GUI.Math.Fortune.Voronoi;
import com.mycompany.worldgenerationproject.GUI.Math.Vector2;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rose_880118
 */
public class VoronoiDisplayPanel extends javax.swing.JPanel
{
    
    Voronoi diagram;

    /**
     * Creates new form VoronoiDisplayPanel
     */
    public VoronoiDisplayPanel()
    {
        initComponents();
        
        diagram = new Voronoi();
        
        List<Vector2> sites = new ArrayList<Vector2>();
        
        /*
        for (int i = 0; i < 2; i++)
        {
            double x = Math.random() * 775;
            double y = Math.random() * 565;
            sites.add(new Vector2(x, y));
        }
        */
        sites.add(new Vector2(200, 200));
        sites.add(new Vector2(200, 400));
        //sites.add(new Vector2(400, 400));
        
        diagram.buildEdges(sites, 775, 565);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void paintComponent(Graphics g)
    {
        
        super.paintComponent(g);
        
        for (VEdge e : diagram.getEdges())
        {
            if (e.getEnd() != null)
            {
                g.drawLine((int)e.getStart().getX(), (int)e.getStart().getY(),
                        (int)e.getEnd().getY(), (int)e.getEnd().getY());
                
                System.out.println(e.getStart().getX());
                System.out.println(e.getStart().getY());
                System.out.println(e.getEnd().getX());
                System.out.println(e.getEnd().getY());
            }
        }
        
    }
    
}
